#!/bin/bash

echo "Copy .env file"
cp .env.example .env

echo "Install composer"
composer install

echo "Create app key"
php artisan key:generate

echo "Create sqlite database"
touch ./database/database.sqlite

echo "Initial migration"
php artisan migrate:fresh

echo "Installation complete!"
